apiVersion: v2
name: ai-landingpage
description: AI Engineering landing page (frontend + backend)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ai
  - landing-page
maintainers: []
