apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-landingpage.fullname" . }}
  labels:
    {{- include "ai-landingpage.labels" . | nindent 4 }}
    app: {{ include "ai-landingpage.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ai-landingpage.selectorLabels" . | nindent 4 }}
    app: {{ include "ai-landingpage.fullname" . }}
